// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Song struct {
	ID          int32
	GroupName   string
	Song        string
	ReleaseDate sql.NullString
	SongText    sql.NullString
	Link        sql.NullString
}
